default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password: <%= ENV.fetch("MY_SQL_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: e-commerce

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: e-commerce