name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEVISE_JWT_SECRET: ${{ secrets.DEVISE_JWT_SECRET }}

    steps:
      # -------------------------
      # CHECKOUT
      # -------------------------

      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------
      # BACKEND - Ruby on Rails
      # -------------------------

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.7"
          working-directory: flowboard-backend_api
          bundler-cache: true

      - name: Prepare test database
        working-directory: flowboard-backend_api
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run RSpec
        working-directory: flowboard-backend_api
        env:
          RAILS_ENV: test
        run: bundle exec rspec

      # -------------------------
      # FRONTEND - Angular
      # -------------------------

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: flowboard/package-lock.json

      - name: Install frontend dependencies
        working-directory: flowboard
        run: npm ci

      - name: Build Angular
        working-directory: flowboard
        run: npm run build