name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:

  ci:
    runs-on: ubuntu-latest

    env:
      DEVISE_JWT_SECRET: ${{ secrets.DEVISE_JWT_SECRET }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.7"
          working-directory: flowboard-backend_api
          bundler-cache: true

      - name: Prepare test database
        working-directory: flowboard-backend_api
        env:
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run RSpec
        working-directory: flowboard-backend_api
        env:
          RAILS_ENV: test
        run: bundle exec rspec


  cd:
    needs: ci
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v7
        with:
          context: ./flowboard-backend_api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flowboard-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v7
        with:
          context: ./flowboard
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flowboard-frontend:latest